name: Cargar datos a Elasticsearch y generar gr치fica

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
        env:
          discovery.type: single-node
          ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        ports:
          - 9200:9200
        options: >-
          --health-cmd="curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v2

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Cargar datos a Elasticsearch
      run: python src/index_data.py

    - name: Generar gr치fica
      run: python src/generate_plot.py

    - name: Subir gr치fica al repositorio
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add docs/index.png
        git commit -m "Auto: agregar gr치fica generada"
        git push
