name: Cargar datos de Elasticsearch y generar grafica

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Asegura permisos de escritura en el contenido
      pull-requests: write  # Permite manejar solicitudes de pull

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v2

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Procesar CSV
      run: python src/index_data.py

    - name: Generar gráfica
      run: python src/generate_plot.py

    - name: Subir gráfica al repositorio si existe
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        if [ -f docs/index.png ]; then
          git add docs/index.png
          git commit -m "Auto: agregar gráfica generada"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        else
          echo "⚠️ El archivo docs/index.png no existe. No se subirá nada."
        fi

    - name: Publicar en GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs

